/*
 **
 **     Boot
 **
 */
async function boot() {
  var boot = [
    "> SET TERMINAL/BOOT",
    "<br>",
    "LOADING",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    "<br>",
    "Checking RAM........",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "Checking PCI Busses.",
    ".",
    ".",
    ".",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> bus0 0x00FF00......[ OK ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> bus1 0x00FF16......[ No Device ]",
    "<br>",
    "Checking SATA-Ports.",
    ".",
    ".",
    ".",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> sata0..............[ OK ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> sata1..............[ OK ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> sata2..............[ No Drive ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> sata3..............[ No Drive ]",
    "<br>",
    "<br>",
    "SEARCHING FOR BOOTABLE MEDIUM",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> sata0..............[ sys ]",
    "<br>",
    "MASTER BOOT RECORD..",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "PLEASE WAIT",
    ".",
    ".",
    ".",
    "",
    "<br>",
    "<br>",
    "clear",
    "> SET TERMINAL/SERVICES",
    "<br>",
    "LOADING",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    "<br>",
    "Starting Floppy Disk Driver.",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "Starting Network Client.....",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "Setting up interface eth0...",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> connected 192.168.0.126",
    "<br>",
    "Checking for Updates........",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "Starting Periphery Driver(s)",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "Detecting Devices...........",
    ".",
    ".",
    ".",
    "[ OK ]",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> usb0 0xFF3409",
    "<br>",
    "&nbsp;",
    "&nbsp;",
    "> usb1 0xFF3509",
    "<br>",
    "<br><br>",
    "> SET TERMINAL/LOGON",
    "<br>",
    "<br>",
    "clear",
    "TERMINAL/LOGON",
    "<br>",
    "<br>",
    "> LOGIN AS 'admin'",
    "<br>",
    "> ENTER PASSWORD ",
    "<br>",
    "input"
  ];
  clear();

  sout(boot);
}
